project:
  type: website

website:
  title: "Lisa Williams Ph.D"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
      - publications.qmd
      - edi.qmd
      - contact.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

