---
title: "About"
---

## Dr. Lisa A. Williams

Dr. Lisa A. Williams is a social psychologist whose research examines the dynamics between emotional experience and social interaction. Much of her research focuses on how positive emotions that arise in the context of social interactions function at the interpersonal, interpersonal, intergroup, and societal levels.

Lisa is currently Professor in the School of Psychology and Associate Dean, Equity Diversity and Inclusion, Faculty of Science, at UNSW Sydney.

Access Lisa’s CV here.

## Dylan Barrett

Dylan commenced his PhD research in the lab in 2024. His project examines the effects of nature exposure on stress and wellbeing using a multi-method approach.

## Amanda Chan

Amanda commenced her PhD research in 2024. Her research explores the role of compassion in reducing mental health stigma via its effects on moral expansiveness.

## June Kam

June completed her Honours thesis research in the lab in 2023. Her project explored public perceptions in the context of shifting blood donation deferral policies for men who have sex with men.

## Kate Nicholls

Kate is a casual research assistant working on projects including emotional processes in the context of blood donation. Kate completed her Honours degree in Psychology at UNSW in 2019 and is currently pursuing her PhD at UNSW.

## Dewa Ayu Puteri

Puteri started her PhD candidature in 2024. Her research examines the role of positive emotions in shaping prosocial behaviour, with a focus on blood donation.
