---
title: "Equity, Diversity and Inclusion"
---

### **Associate Dean, Equity Diversity and Inclusion, UNSW Faculty of Science**

Lisa serves as co-Associate Dean Equity Diversity and Inclusion in the UNSW Faculty of Science. She has held this role since 2019. Key initiatives include a carer support scheme, a career support scheme for women, and flexible work guidelines. More information on these activities and more is available [here](https://www.unsw.edu.au/science/about-us/equity-diversity-inclusion).

------------------------------------------------------------------------

### **Program Director, Future You**

Lisa is currently Program Director for [Future You](https://futureyouaustralia.com/), a program designed to promote interest in STEM careers among kids aged 8-12 years. A core remit of the program is to support teachers and parents to inspire kids whose identities are typically underrepresented in STEM to pursue STEM careers. The program is supported by [Optiver Foundation](https://www.unsw.edu.au/newsroom/news/2025/03/UNSW-receives-2m-Optiver-Foundation-grant-to-boost-diversity-in-STEM), the UNSW Faculty of Science, and the University of Sydney Faculty of Science.

------------------------------------------------------------------------

### **Chief Investigator, Office for Australia’s Women in STEM Ambassador**

Lisa was Chief Investigator on the grants that funded the Office for Australia’s Women in STEM Ambassador, awarded by the Australian Government. From 2021-2024, Lisa worked alongside the Ambassador, Professor Lisa Harvey-Smith, to deploy key initiatives to improve participation of women and girls in STEM. Research activities included an analysis of 20 years of Australian government grants data to examine trends in gender equity over time, a systematic review of equity initiatives, and an empirical examination of the efficacy of a digital campaign [Future You](https://futureyouaustralia.com/) in promoting interest in STEM careers. More about the Office and its activities can be found [here](https://www.unsw.edu.au/science/engage-with-us/women-stem-ambassador-program).

------------------------------------------------------------------------

### **UNSW Self-Assessment Team, SAGE Athena Swan**

From 2015-2019, Lisa served on the UNSW SAGE Athena Swan Self-Assessment Team. She led a subgroup examining career development offerings and uptake, served as lead-researcher for the Staff Survey, and played an integral role in developing and writing UNSW’s Bronze Award Application. She also facilitated an analysis of potential gender disparities in grant applications to the Australian Research Council and the National Health and Medical Research Council.
