---
title: "Publications"
---

## **in press**

Kingsley, I., Slavich, E., Harvey-Smith, L., Johnston, E. L. & Williams, L. A. (in press). Women are awarded more team than solo grants and lead more gender-balanced teams than men. *Science and Public Policy.* DOI: [10.1093/scipol/scae064](https://doi.org/10.1093/scipol/scae064)

## **2024**

Iannuzzelli, R., Gonsalkorale, K., & Williams, L. A. (2024). Motives matter: The psychological experience of ostracizing among sources. *PLoS ONE, 19*(5): e0303510*.* DOI: [10.1371/journal.pone.0303510](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0303510)

Kim, F., Williams, L. A., Johnston, E., & Fan, Y. (2024). Bias intervention messaging in student evaluations of teaching: The role of gendered perceptions of bias. *Heliyon, 10*(17), e37140*.* DOI:[ ](https://www.cell.com/heliyon/fulltext/S2405-8440(24)13171-4)[10.1016/j.heliyon.2024.e37140](https://doi.org/10.1016/j.heliyon.2024.e37140)

Williams, L. A., Nicholls, K., & Williams, J. R. W. (2024) Psychological responses to blood donated by men who have sex with men. *Blood Transfusion, 22*(2), 96-105*.* DOI: [10.2450/BloodTransfus.481](https://doi.org/10.2450/BloodTransfus.481)

Williams, L. A., Tzelios, K., Masser, B., Thijsen, A., van Dongen, A., & Davison, T. (2024). A virtual reality paradigm simulating blood donation serves as a platform to test interventions to promote donation. *Scientific Reports, 14*(1), 10334. DOI: [10.1038/s41598-024-60578-6](https://www.nature.com/articles/s41598-024-60578-6)

## **2023**

Ferguson, E., Lawrence, C., Bowen, S., Gemelli, C. N., Rozsa, A., Niekrasz, K., van Dongen, A., Williams, L. A., Thijsen, A., Guerin, N., Masser, B., & Davison, T. E. Warming up cool cooperators. *Nature Human Behavior*, *7*, 1917–1932. DOI: [10.1038/s41562-023-01687-6](https://www.nature.com/articles/s41562-023-01687-6)

Marey, T., Tzelios, K., Williams, L. A., & Baker, S. Equity and STEM in elite contexts: Challenging institutional assumptions about students in Australia. *International Journal of Inclusive Education, 27*(14), 1576-1591*.* DOI: [10.1080/13603116.2021.1904016](https://www.tandfonline.com/doi/abs/10.1080/13603116.2021.1904016)

Thijsen, A., Masser, B., Davison, T. E., van Dongen, A., & Williams, L. A. (2023). Beyond fear: A longitudinal investigation of emotions and risk of a vasovagal reaction in first-time whole-blood donors. *Transfusion, 63*(1). DOI: [10.1111/trf.17169](https://onlinelibrary.wiley.com/doi/full/10.1111/trf.17169)

## **2022**

Tzelios, K., Williams, L. A., Omerod, J., & Bliss-Moreau, E. (2022). Evidence of the unidimensional structure of mind perception*. Scientific Reports*, 12. DOI: [10.1038/s41598-022-23047-6](https://www.nature.com/articles/s41598-022-23047-6)

## **2021**

Gruber, J., Mendle, J., … Williams, L. A. (2021). The future of women in psychological science. *Perspectives on Psychological Science*, *16*(3), 483-516. DOI: [10.1177/1745691620952789](https://journals.sagepub.com/doi/full/10.1177/1745691620952789)

Van Dongen, A., Williams, L. A., Masser, B., Briggs, N., Thijsen, A., Davison, T. E. (2021). The impact of temporal trajectories of emotional experience on blood donor return. *Annals of Behavioral Medicine, 55*(7), 686-692. DOI: [10.1093/abm/kaaa067/5908313](https://academic.oup.com/abm/advance-article/doi/10.1093/abm/kaaa067/5908313)

Williams, L. A. (2021). From wellbeing to welfare. *Neuroscience and Biobehavioral Reviews*, 131, 941-952. DOI: [10.1016/j.neubiorev.2021.09.014](https://www.sciencedirect.com/science/article/pii/S0149763421003973)

## **2020**

Bliss-Moreau, E., Santistevan, A. C., & Williams, L. A. (2020). The immutability of valence and arousal in the foundation of emotion. *Emotion, 20*(6), 993-1004. DOI: [10.1037/emo0000606](https://pubmed.ncbi.nlm.nih.gov/31192659/)

France, C., France, J., Himawan, L., Jeitani, A., & Williams, L. A. (2020). Emotional mechanisms and format effects of motivational questions for blood donation. *Transfusion, 60*(9), 1998-2009. DOI: [10.1111/trf.15942](https://onlinelibrary.wiley.com/doi/abs/10.1111/trf.15942)

Masser, B., Ferguson, E., Merz, E., & Williams, L. A. (2020). Beyond description – the predictive role of affect, memory, and context on the decision to donate or not donate blood. *Transfusion Medicine & Hemotherapy, 47*, 175-185. DOI: [10.1159/000501917](https://pubmed.ncbi.nlm.nih.gov/32355478/)

Tzelios, K., & Williams, L. A. (2020). The Psychological Impact of Digital Signatures: A Multi-study Replication. *Technology, Mind, and Behavior, 1*(2). DOI: [10.1037/tmb0000019](https://tmb.apaopen.org/pub/ba1x1zjo/release/3)

Williams, L. A., Brosnan, S. F., & Clay, Z. (2020). Anthropomorphism in comparative affective science: Advocating a mindful approach. *Neuroscience and Biobehavioral Reviews, 115*, 299-307. DOI: [10.1016/j.neubiorev.2020.05.014](https://pubmed.ncbi.nlm.nih.gov/32497569/)

## **2019**

Williams, L. A., Sun, J., & Masser, B. (2019). Integrating Self-Determination Theory and the Theory of Planned Behaviour to predict intention to donate blood. *Transfusion Medicine, 29*(S1), 59-64. DOI: [10.1111/tme.12566](https://onlinelibrary.wiley.com/doi/abs/10.1111/tme.12566)

## **2018**

Klein, R. A., Vianello, M., …. Williams, L. A., …, Nosek, B. A. (2018). Many Labs 2: Investigating variation in replicability across sample and setting (Registered Replication Report). *Advances in Methods and Practices in Psychological Science, 1*(4), 443-490. DOI: [10.1177/2515245918810225](https://journals.sagepub.com/doi/full/10.1177/2515245918810225)

Bliss-Moreau, E., Karaskiewicz, C., & Williams, L. A. (2018). Evolution of emotion in social context. In T. Hackelford & V. Weekes-Shackelford (Eds.), *Encyclopedia of Evolutionary Psychological Science*. Cham: Springer. DOI: [10.1007/978-3-319-16999-6_2459-1](https://link.springer.com/referenceworkentry/10.1007%2F978-3-319-16999-6_2459-1)

Garg, N., Williams, L. A., & Lerner, J. (2018). The Misery-Is-Not-Miserly Effect revisited: Replication in the face of hedonic consumption. *PLOS ONE, 13*(6), e0199433. DOI: [10.1371/journal.pone.0199433](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199433)

Greenaway, K. H., Kalokerinos, E. K., & Williams, L. A. (2018). Context is everything (in emotion research). *Social and Personality Psychology Compass, 12*(6), e12393. DOI: [10.1111/spc3.12393](https://onlinelibrary.wiley.com/doi/abs/10.1111/spc3.12393)

Williams, L. A. (2018). Emotions of excellence: The communal and agentic functions of pride, moral elevation, and admiration. In H. Lench (Ed.), *The Functions of Emotion* (pp. 235-252). Cham: Springer. DOI: [10.1007/978-3-319-77619-4_12](https://link.springer.com/chapter/10.1007/978-3-319-77619-4_12)

Williams, L. A., Masser, B., van Dongen, A., Thijsen, A., & Davison, T. (2018). The emotional psychology of blood donors: A time-course approach. *ISBT Science Series/Vox Sanguinis*, 13(1), 93-100. DOI: [10.1111/voxs.12385](https://onlinelibrary.wiley.com/doi/full/10.1111/voxs.12385)

## **2017**

Crone, D., & Williams, L. A. (2017). Crowdsourcing participants for psychological research in Australia: A test of Microworkers. *Australian Journal of Psychology, 69*(1), 39-47. DOI: [10.1111/ajpy.12110](https://aps.onlinelibrary.wiley.com/doi/abs/10.1111/ajpy.12110)

Williams, L. A., & Davies, J. (2017). [Beyond the self: Pride felt in relation to others](https://psycnet.apa.org/record/2019-14416-004). In J. A. Carter & E. C. Gordon (Eds.), *The Moral Psychology of Pride* (pp. 43-68) (part of The Moral Psychology of Emotions Series). London: Rowman & Littlefield.

Williams, L. A., Schofield, T. P., & Whitford, T. J. (2017). Romantic red: Testing the characteristics of color-attraction effects in a novel paradigm. *Collabra: Psychology, 3*(1), 10. DOI: [10.1525/collabra.54](https://online.ucpress.edu/collabra/article/3/1/10/112367/Romantic-Red-Testing-the-Characteristics-of-Color)

## **2016**

Barrett-Cheetham, E., Williams, L. A., & Bednall, T. (2016). A differentiated approach to the link between positive emotion and wellbeing. *Journal of Positive Psychology, 11*(6), 595-608. DOI: [10.1080/17439760.2016.1152502](https://www.tandfonline.com/doi/abs/10.1080/17439760.2016.1152502?journalCode=rpos20)

Williams, L. A., & Bliss-Moreau, E. (2016). Humans are ultrasocial and emotional. *Behavioral and Brain Sciences, 39*, 39-40. DOI: [10.1017/S0140525X15001211](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/abs/humans-are-ultrasocial-and-emotional/7E30F7AA8263D2E04B22D0B78E12885F)

## **2015**

Gooley, S. L., Zadro, L., Williams, L. A., \*Svetieva, E., & Gonsalkorale, K. (2015). Ostracizing for a reason: A novel source paradigm for examining the nature and consequences of motivated ostracism. *Journal of Social Psychology, 155*(5), 410-431. DOI: [10.1080/00224545.2015.1060933](https://www.tandfonline.com/doi/abs/10.1080/00224545.2015.1060933?journalCode=vsoc20)

Williams, L. A., & Barrett-Cheetham, E. (2015). Social psychological perspectives on compassion. In M. Brenner (Ed.), *Conversations on Compassion*. Createspace Publishers.

Williams, L. A., & Bartlett, M. Y. (2015). Warm thanks: Gratitude expression facilitates social affiliation in new relationships via perceived warmth. *Emotion, 15*(1), 1-5. DOI: [10.1037/emo0000017](https://pubmed.ncbi.nlm.nih.gov/25111881/)

Williams, L. A., Masser, B., & Sun, J. (2015). Revisiting the effect of anthropomorphizing a social campaign. *PLOS ONE, 10*(9): e0138886. DOI: [10.1371/journal.pone.0138886](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0138886)

## **2014**

Bliss-Moreau, E., & Williams, L. A. (2014). Tag, you’re it: Affect tagging promotes goal formation and selection. *Behavioral and Brain Sciences, 37*(2), 138-139. DOI: [10.1017/S0140525X13001969](https://www.cambridge.org/core/journals/behavioral-and-brain-sciences/article/abs/tag-youre-it-affect-tagging-promotes-goal-formation-and-selection/1480334BB3B1569D1094211C67F66B51)

Masser, B., Smith, G., & Williams, L. A. (2014). Donor research in Australia: Challenges and promise. *Transfusion Medicine & Hemotherapy, 41*, 296-301. DOI: [10.1159/000365016](https://www.karger.com/Article/FullText/365016)

Williams, L. A., & DeSteno, D. (2014). How positive social emotions motivate actions for the future self: Building bonds, attaining ambitions, and establishing esteem. In J. Gruber & J. T. Moskowitz (Eds.), *Positive Emotion: Integrating the Light Sides and Dark Sides* (pp. 206-224). New York: Oxford University Press. DOI: [10.1093/acprof:oso/9780199926725.003.0012](https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780199926725.001.0001/acprof-9780199926725-chapter-12)

## **2010**

DeSteno, D., Bartlett, M. Y., Baumann, J., Williams, L. A., & Dickens, L. (2010). Gratitude as moral sentiment: Emotion-guided cooperation in economic exchange. *Emotion, 2*, 289-293. DOI: [10.1037/a0017883](https://pubmed.ncbi.nlm.nih.gov/20364907/)

Williams, L. A., & DeSteno, D. (2010). Pride in parsimony. *Emotion Review, 2*, 180-181. DOI: [10.1177/1754073909355015](https://journals.sagepub.com/doi/10.1177/1754073909355015)

## **2009**

Dasgupta, N., DeSteno, D., Williams, L. A., & Hunsinger, M. (2009). Fanning the flames of prejudice: The influence of specific incidental emotions on implicit prejudice. *Emotion, 9,* 585-591. DOI: [10.1037/a0015961](https://pubmed.ncbi.nlm.nih.gov/19653784/)

Williams, L. A., & DeSteno, D. (2009). Pride: Adaptive social emotion or seventh sin? *Psychological Science, 20*, 284-288. DOI: [10.1111/j.1467-9280.2009.02292.x](https://journals.sagepub.com/doi/10.1111/j.1467-9280.2009.02292.x)

## **2008**

Williams, L. A., & DeSteno, D. (2008). Pride and perseverance: The motivational function of pride. *Journal of Personality and Social Psychology, 94*, 1007-1017. DOI: [10.1037/0022-3514.94.6.1007](https://pubmed.ncbi.nlm.nih.gov/18505314/)
